# Generated by Django 5.0.14 on 2025-12-18 07:31

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AgentApplication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("agent_id", models.CharField(max_length=50, unique=True)),
                (
                    "applicant_role",
                    models.CharField(
                        choices=[
                            ("FO", "Field Officer"),
                            ("FM", "Field Manager"),
                            ("DGM", "Deputy General Manager"),
                            ("GM", "General Manager"),
                        ],
                        max_length=10,
                    ),
                ),
                ("fm_name", models.CharField(max_length=200)),
                ("role_code", models.CharField(max_length=50)),
                ("dgm_name", models.CharField(max_length=200)),
                ("dgm_code", models.CharField(max_length=50)),
                ("gm_name", models.CharField(max_length=200)),
                ("gm_code", models.CharField(max_length=50)),
                ("full_name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                (
                    "phone",
                    models.CharField(
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Provide a valid phone number",
                                regex="^[0-9+\\-()\\s]{8,20}$",
                            )
                        ],
                    ),
                ),
                ("address", models.TextField()),
                ("guardian_name", models.CharField(max_length=200)),
                ("mother_name", models.CharField(max_length=200)),
                ("present_address", models.TextField()),
                ("permanent_address", models.TextField()),
                ("dob", models.DateField()),
                ("birth_place", models.CharField(max_length=120)),
                ("nid_number", models.CharField(max_length=40)),
                ("bank_account_number", models.CharField(max_length=60)),
                ("bank_name", models.CharField(max_length=120)),
                ("bank_branch_name", models.CharField(max_length=120)),
                (
                    "applicant_photo",
                    models.ImageField(
                        upload_to="agents/photos/%Y/%m/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["jpg", "jpeg", "png"]
                            )
                        ],
                    ),
                ),
                (
                    "nid_document",
                    models.FileField(
                        upload_to="agents/nid/%Y/%m/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["jpg", "jpeg", "png", "pdf"]
                            )
                        ],
                    ),
                ),
                (
                    "education_certificate",
                    models.FileField(
                        upload_to="agents/education/%Y/%m/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["jpg", "jpeg", "png", "pdf"]
                            )
                        ],
                    ),
                ),
                ("password_hash", models.CharField(max_length=128)),
                ("agree_terms", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("under_review", "Under Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("reviewed_by", models.CharField(blank=True, max_length=150)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("user_agent", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Agent Application",
                "verbose_name_plural": "Agent Applications",
                "ordering": ["-submitted_at"],
                "indexes": [
                    models.Index(
                        fields=["agent_id"], name="agents_agen_agent_i_3b47db_idx"
                    ),
                    models.Index(
                        fields=["status"], name="agents_agen_status_533de2_idx"
                    ),
                    models.Index(
                        fields=["-submitted_at"], name="agents_agen_submitt_28ca86_idx"
                    ),
                ],
            },
        ),
    ]
