# Generated by Django 5.2.8 on 2025-11-17 13:13

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('proposal_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('under_review', 'Under Review')], default='pending', max_length=20)),
                ('membership_type', models.CharField(choices=[('individual', 'Individual Membership'), ('family', 'Family Membership'), ('corporate', 'Corporate Membership')], max_length=20)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('age', models.IntegerField(editable=False, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('marital_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=20)),
                ('mobile_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('emergency_contact_name', models.CharField(max_length=200)),
                ('emergency_contact_number', models.CharField(max_length=20)),
                ('nid_number', models.CharField(max_length=50, unique=True)),
                ('passport_number', models.CharField(blank=True, max_length=50)),
                ('occupation', models.CharField(max_length=200)),
                ('organization_name', models.CharField(blank=True, max_length=200)),
                ('monthly_income', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('spouse_name', models.CharField(blank=True, max_length=200)),
                ('number_of_children', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('father_name', models.CharField(max_length=200)),
                ('mother_name', models.CharField(max_length=200)),
                ('photo', models.ImageField(help_text='Passport-size photo (JPG/PNG, max 5MB)', upload_to='photos/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])])),
                ('age_proof', models.FileField(help_text='Birth certificate or NID (PDF/Image, max 5MB)', upload_to='documents/age_proof/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])])),
                ('driving_license', models.FileField(blank=True, help_text='Driving license (optional, PDF/Image, max 5MB)', null=True, upload_to='documents/licenses/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])])),
                ('present_address', models.TextField(help_text='Full present address')),
                ('permanent_address', models.TextField(help_text='Full permanent address')),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight in kg', max_digits=5, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(500)])),
                ('height', models.DecimalField(decimal_places=2, help_text='Height in cm', max_digits=5, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(300)])),
                ('blood_group', models.CharField(choices=[('A+', 'A Positive'), ('A-', 'A Negative'), ('B+', 'B Positive'), ('B-', 'B Negative'), ('AB+', 'AB Positive'), ('AB-', 'AB Negative'), ('O+', 'O Positive'), ('O-', 'O Negative')], max_length=3)),
                ('surgery_history', models.TextField(blank=True, help_text='List any previous surgeries (optional)')),
                ('medical_records', models.FileField(blank=True, help_text='Medical records (optional, PDF/Image, max 5MB)', null=True, upload_to='documents/medical/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])])),
                ('prescription', models.FileField(blank=True, help_text='Current prescriptions (optional, PDF/Image, max 5MB)', null=True, upload_to='documents/prescriptions/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])])),
                ('terms_accepted', models.BooleanField(default=False)),
                ('declaration_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Membership Application',
                'verbose_name_plural': 'Membership Applications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='membership__created_80e201_idx'), models.Index(fields=['status'], name='membership__status_fddb44_idx'), models.Index(fields=['proposal_number'], name='membership__proposa_62196f_idx'), models.Index(fields=['nid_number'], name='membership__nid_num_cecdc1_idx')],
            },
        ),
        migrations.CreateModel(
            name='ApplicationStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('changed_by', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='membership.membershipapplication')),
            ],
            options={
                'verbose_name': 'Status History',
                'verbose_name_plural': 'Status Histories',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Nominee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('relationship', models.CharField(choices=[('spouse', 'Spouse'), ('father', 'Father'), ('mother', 'Mother'), ('son', 'Son'), ('daughter', 'Daughter'), ('brother', 'Brother'), ('sister', 'Sister'), ('other', 'Other')], max_length=20)),
                ('mobile_number', models.CharField(max_length=20)),
                ('nid_number', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('share_percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('id_proof', models.FileField(help_text='NID or other ID proof (PDF/Image, max 5MB)', upload_to='documents/nominee_id/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominees', to='membership.membershipapplication')),
            ],
            options={
                'verbose_name': 'Nominee',
                'verbose_name_plural': 'Nominees',
                'ordering': ['id'],
            },
        ),
    ]
