# Generated by Django 5.0.14 on 2025-11-17 14:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membershipapplication",
            name="age_proof",
            field=models.FileField(
                blank=True,
                help_text="Birth certificate or NID (PDF/Image, max 5MB)",
                null=True,
                upload_to="documents/age_proof/%Y/%m/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["pdf", "jpg", "jpeg", "png"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="membershipapplication",
            name="blood_group",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A+", "A Positive"),
                    ("A-", "A Negative"),
                    ("B+", "B Positive"),
                    ("B-", "B Negative"),
                    ("AB+", "AB Positive"),
                    ("AB-", "AB Negative"),
                    ("O+", "O Positive"),
                    ("O-", "O Negative"),
                ],
                default="",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="membershipapplication",
            name="height",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Height in cm",
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(50),
                    django.core.validators.MaxValueValidator(300),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="membershipapplication",
            name="permanent_address",
            field=models.TextField(
                blank=True, default="", help_text="Full permanent address"
            ),
        ),
        migrations.AlterField(
            model_name="membershipapplication",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Passport-size photo (JPG/PNG, max 5MB)",
                null=True,
                upload_to="photos/%Y/%m/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="membershipapplication",
            name="present_address",
            field=models.TextField(
                blank=True, default="", help_text="Full present address"
            ),
        ),
        migrations.AlterField(
            model_name="membershipapplication",
            name="weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Weight in kg",
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(10),
                    django.core.validators.MaxValueValidator(500),
                ],
            ),
        ),
    ]
