# Generated by Django 5.0.14 on 2025-11-22 17:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0002_alter_membershipapplication_age_proof_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="membershipapplication",
            name="medical_records",
        ),
        migrations.RemoveField(
            model_name="membershipapplication",
            name="prescription",
        ),
        migrations.RemoveField(
            model_name="membershipapplication",
            name="surgery_history",
        ),
        migrations.AddField(
            model_name="membershipapplication",
            name="accept_terms",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="membershipapplication",
            name="age_proof_doc",
            field=models.FileField(
                blank=True,
                help_text="Age proof document (PDF/Image, max 5MB)",
                null=True,
                upload_to="documents/age_proof/%Y/%m/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["pdf", "jpg", "jpeg", "png"]
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="membershipapplication",
            name="chest",
            field=models.CharField(
                blank=True, help_text="Chest in inches", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="membershipapplication",
            name="daily_work",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="membershipapplication",
            name="dob",
            field=models.DateField(blank=True, help_text="Date of birth", null=True),
        ),
        migrations.AddField(
            model_name="membershipapplication",
            name="education",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="membershipapplication",
            name="fo_code",
            field=models.CharField(
                blank=True, help_text="Field Officer Code", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="membershipapplication",
            name="fo_name",
            field=models.CharField(
                blank=True, help_text="Field Officer Name", max_length=200, null=True
            ),
        ),
        migrations.AddField(
            model_name="membershipapplication",
            name="income_source",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="membershipapplication",
            name="license_doc",
            field=models.FileField(
                blank=True,
                help_text="Driving license document (optional, PDF/Image, max 5MB)",
                null=True,
                upload_to="documents/licenses/%Y/%m/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["pdf", "jpg", "jpeg", "png"]
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="membershipapplication",
            name="mobile",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Format: +880XXXXXXXXXX",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="membershipapplication",
            name="name_bangla",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="membershipapplication",
            name="name_english",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="membershipapplication",
            name="nationality",
            field=models.CharField(default="Bangladeshi", max_length=100),
        ),
        migrations.AddField(
            model_name="membershipapplication",
            name="organization_details",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="membershipapplication",
            name="professional_qualifications",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="membershipapplication",
            name="proposal_no",
            field=models.CharField(
                blank=True, default="", editable=False, max_length=100, unique=True
            ),
        ),
        migrations.AddField(
            model_name="membershipapplication",
            name="surgery_details",
            field=models.TextField(
                blank=True, help_text="List any previous surgeries (optional)"
            ),
        ),
        migrations.AddField(
            model_name="nominee",
            name="age",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="nominee",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Nominee photo",
                null=True,
                upload_to="nominee_photos/%Y/%m/",
            ),
        ),
        migrations.AddField(
            model_name="nominee",
            name="relation",
            field=models.CharField(
                blank=True, help_text="Original relation from frontend", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="nominee",
            name="share",
            field=models.IntegerField(
                default=0,
                help_text="Percentage share",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="membershipapplication",
            name="age",
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="membershipapplication",
            name="age_proof",
            field=models.JSONField(
                default=list, help_text="Array of selected proof types"
            ),
        ),
        migrations.AlterField(
            model_name="membershipapplication",
            name="date_of_birth",
            field=models.DateField(blank=True, help_text="Legacy field", null=True),
        ),
        migrations.AlterField(
            model_name="membershipapplication",
            name="driving_license",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No")], default="no", max_length=3
            ),
        ),
        migrations.AlterField(
            model_name="membershipapplication",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="membershipapplication",
            name="emergency_contact_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="membershipapplication",
            name="emergency_contact_number",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="membershipapplication",
            name="father_name",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="membershipapplication",
            name="first_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="membershipapplication",
            name="height",
            field=models.CharField(
                blank=True, help_text='Height in feet (e.g., "5\'8"")', max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="membershipapplication",
            name="last_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="membershipapplication",
            name="mobile_number",
            field=models.CharField(blank=True, help_text="Legacy field", max_length=20),
        ),
        migrations.AlterField(
            model_name="membershipapplication",
            name="mother_name",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="membershipapplication",
            name="nid_number",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="membershipapplication",
            name="number_of_children",
            field=models.IntegerField(
                blank=True,
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(20),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="membershipapplication",
            name="occupation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("service", "Service"),
                    ("business", "Business"),
                    ("farmer", "Farmer"),
                    ("others", "Others"),
                ],
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="membershipapplication",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Passport-size photo (JPG/PNG, max 2MB)",
                null=True,
                upload_to="photos/%Y/%m/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="membershipapplication",
            name="spouse_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="membershipapplication",
            name="terms_accepted",
            field=models.BooleanField(default=False, help_text="Legacy field"),
        ),
        migrations.AlterField(
            model_name="membershipapplication",
            name="weight",
            field=models.CharField(
                blank=True, help_text='Weight in kg (e.g., "70.5")', max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="nominee",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="nominee",
            name="id_proof",
            field=models.FileField(
                blank=True,
                help_text="NID or other ID proof (PDF/Image, max 5MB)",
                null=True,
                upload_to="nominee_id/%Y/%m/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["pdf", "jpg", "jpeg", "png"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="nominee",
            name="mobile_number",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="nominee",
            name="nid_number",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="nominee",
            name="relationship",
            field=models.CharField(
                choices=[
                    ("child", "Child"),
                    ("spouse", "Spouse"),
                    ("father", "Father"),
                    ("mother", "Mother"),
                    ("sibling", "Sibling"),
                ],
                default="child",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="nominee",
            name="share_percentage",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Legacy field",
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.CreateModel(
            name="MedicalRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Medical record file (PDF/Image, max 5MB)",
                        upload_to="medical_records/%Y/%m/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["pdf", "jpg", "jpeg", "png"]
                            )
                        ],
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_records_files",
                        to="membership.membershipapplication",
                    ),
                ),
            ],
            options={
                "db_table": "medical_records",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
