# Generated by Django 5.0.14 on 2025-11-22 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0003_remove_membershipapplication_medical_records_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membershipapplication",
            name="monthly_income",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
    ]
