# Generated by Django 5.0.14 on 2025-06-01 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0004_alter_membershipapplication_monthly_income"),
    ]

    operations = [
        migrations.AddField(
            model_name="membershipapplication",
            name="valid_until",
            field=models.DateField(
                blank=True,
                help_text="Membership validity date",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="membershipapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Review"),
                    ("approved", "Approved"),
                    ("active", "Active"),
                    ("rejected", "Rejected"),
                    ("under_review", "Under Review"),
                    ("expired", "Expired"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="membershipapplication",
            index=models.Index(fields=["dob"], name="membership__dob_3a5f7c_idx"),
        ),
    ]
