# Generated by Django 5.0.14 on 2025-12-04 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0005_membershipapplication_valid_until_and_more"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="membershipapplication",
            new_name="membership__dob_f1a93d_idx",
            old_name="membership__dob_3a5f7c_idx",
        ),
        migrations.AddIndex(
            model_name="membershipapplication",
            index=models.Index(
                fields=["proposal_no"], name="membership__proposa_86215d_idx"
            ),
        ),
    ]
