# Generated by Django 5.0.14 on 2025-11-22 22:12

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("membership", "0004_alter_membershipapplication_monthly_income"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentProof",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        help_text="Transaction/Reference ID from payment",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("touch-n-go", "Touch n Go eWallet"),
                            ("bkash", "Bkash"),
                            ("bank-transfer", "Bank Transfer"),
                        ],
                        help_text="Payment method used",
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Payment amount",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                (
                    "payer_name",
                    models.CharField(
                        help_text="Name of person who made payment", max_length=200
                    ),
                ),
                (
                    "payer_contact",
                    models.CharField(
                        help_text="Contact number of payer", max_length=50
                    ),
                ),
                (
                    "screenshot",
                    models.ImageField(
                        blank=True,
                        help_text="Payment screenshot/receipt (max 5MB)",
                        null=True,
                        upload_to="payment_proofs/%Y/%m/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["jpg", "jpeg", "png", "pdf"]
                            )
                        ],
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes or comments",
                        max_length=500,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Verification"),
                            ("verified", "Verified"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        help_text="Verification status",
                        max_length=20,
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when payment was verified",
                        null=True,
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True, help_text="Reason for rejection (if rejected)"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address of submitter", null=True
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, help_text="Browser user agent"),
                ),
                (
                    "membership_application",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated membership application",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_proofs",
                        to="membership.membershipapplication",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin user who verified the payment",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Proof",
                "verbose_name_plural": "Payment Proofs",
                "ordering": ["-submitted_at"],
                "indexes": [
                    models.Index(
                        fields=["-submitted_at"], name="payment_pay_submitt_8a1e89_idx"
                    ),
                    models.Index(
                        fields=["transaction_id"], name="payment_pay_transac_51bd1e_idx"
                    ),
                    models.Index(
                        fields=["status"], name="payment_pay_status_c4ab40_idx"
                    ),
                ],
            },
        ),
    ]
